---
- name: Install pip3 package
  package:
    update_cache: yes 
    name: python3-pip
    state: latest

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3	
#    delegate_to: localhost

- name: build docker image
  docker_image:
    build:
      path: "{{ app_dir }}/flask_app"
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    source: build
  vars:
    ansible_python_interpreter: /bin/python3    

- name: Create container
  docker_container:
    name: flask1
    image: "{{ image_name }}:{{ image_tag }}"
    exposed_ports: 
      - 5000:5000
    published_ports:
      - "5001:5000"
    detach: true
    restart_policy: on-failure
    interactive: true
    state: started

- name: Create container
  docker_container:
    name: flask2
    image: "{{ image_name }}:{{ image_tag }}"
    exposed_ports: 
      - 5000:5000
    published_ports:
      - "5002:5000"
    detach: true
    restart_policy: on-failure
    interactive: true
    state: started